name: "macos balance alpine CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month 



jobs:

  balance-macos-latest:
      name: "balance  macos-latest"
      runs-on: macos-latest # not OK
      # runs-on: macos-11 # not OK
      # runs-on: macos-10.15 # not OK
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update     
      - name: "check on brew version"
        run: brew --version               
      - name: "install balance"
        run: brew install balance            
      - name: "brew cask list"
        run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
      - name: "brew list --formula"
        run: brew list --formula #List all the installed formulas
      - name: "Get OS X System Version"
        run: sw_vers       
      - name: "Get Mac System Details with system_profiler"
        run: system_profiler | more  
      - name: "osfingerprinting"
        run: uname -a 
      - name: "run balance"
        run: balance -f 8888 host1 10.1.1.1:8000    
